const dataFile = await d3.csv("data/routes.csv");

// define colors for airlines, you can expand this as needed, WN is Southwest, B6 is JetBlue
const airlineColor = { WN: "orange", B6: "steelblue" };
const airlineName = { WN: "Southwest Airlines", B6: "JetBlue" };

// create options from selector that allows us to view all airlines or filter by a specific airline
const airlines = ["all", ...new Set(dataFile.map(d => d.Airline))];

// build selector from data
const select = d3.select("body")
    .insert("select", "#chart")
    .on("change", function () { draw(this.value); });

select.selectAll("option")
    .data(airlines)
    .join("option")
    .attr("value", d => d)
    .text(d => d === "all" ? "All Airlines" : airlineName[d] ?? d);

// helper function to build outgoing links for each leaf node
function bilink(root) {
    // create a map of leaf nodes for quick lookup, using the unique ID generated by the id() function
    const map = new Map(root.leaves().map(d => [id(d), d]));

    // for each leaf node, build an outgoing array of [source, target, airline] tuples
    for (const d of root.leaves()) {
        d.incoming = [];
        d.outgoing = (d.data.destinations ?? [])
            .map(({ target, airline, targetRegion }) => [d, map.get(`root/${targetRegion}/${target}`), airline])
            .filter(([, target]) => target !== undefined);
    }

    for (const d of root.leaves()) {
        for (const route of d.outgoing) {
            route[1].incoming.push(route);
        }
    }

    return root;
}

// helper function to generate a unique ID for each node based on its position in the hierarchy
function id(node) {
    return `${node.parent ? id(node.parent) + "/" : ""}${node.data.name}`;
}

//rebuild hierarchy data and redraw chart on selection change
function draw(airlineFilter) {

    // filter data based on selection, if "all" is selected, use the entire dataset
    const filtered = airlineFilter === "all"
        ? dataFile
        : dataFile.filter(d => d.Airline === airlineFilter);

    const airportMap = new Map();

    for (const route of filtered) {
        const sourceAirport = route["Source airport"];
        const destinationAirport = route["Destination airport"];
        const sourceRegion = route["Source region"];
        const destinationRegion = route["Destination region"];

        if (!airportMap.has(sourceAirport)) {
            airportMap.set(sourceAirport, {
                name: sourceAirport,
                region: sourceRegion,
                destinations: []
            });
        }

        if (!airportMap.has(destinationAirport)) {
            airportMap.set(destinationAirport, {
                name: destinationAirport,
                region: destinationRegion,
                destinations: []
            });
        }

        airportMap.get(sourceAirport).destinations.push({
            target: destinationAirport,
            airline: route.Airline,
            targetRegion: destinationRegion
        });
    }

    // group airports by region so the hierarchy includes destination-only airports as leaves
    const grouped = d3.group(Array.from(airportMap.values()), d => d.region);

    // transform grouped data into a hierarchy format suitable for the chart
    const hierarchyData = {
        name: "root",
        children: Array.from(grouped, ([region, airports]) => ({
            name: region,
            children: airports
        }))
    };

    document.getElementById("chart").innerHTML = "";
    document.getElementById("chart").appendChild(createChart(hierarchyData));
}

draw("all"); // initial draw

function createChart(data) {
    const width = 954;
    const radius = width / 2;

    const tree = d3.cluster().size([2 * Math.PI, radius - 100]);
    const line = d3.lineRadial()
        .curve(d3.curveBundle.beta(0.85))
        .radius(d => d.y)
        .angle(d => d.x);

    const root = tree(
        bilink(
            d3.hierarchy(data)
                .sort((a, b) => d3.ascending(a.height, b.height) || d3.ascending(a.data.name, b.data.name))
        )
    );

    const svg = d3.create("svg")
        .attr("width", width)
        .attr("height", width)
        .attr("viewBox", [-width / 2, -width / 2, width, width])
        .style("max-width", "100%")
        .style("height", "auto")
        .style("display", "block")
        .style("margin", "0 auto")
        .style("font", "10px sans-serif");

    const link = svg.append("g")
        .attr("fill", "none")
        .selectAll("path")
        .data(root.leaves().flatMap(leaf => leaf.outgoing))
        .join("path")
        .style("mix-blend-mode", "multiply")
        .attr("stroke", ([, , airline]) => airlineColor[airline] ?? "#444")
        .attr("stroke-opacity", 0.55)
        .attr("d", ([source, target]) => line(source.path(target)))
        .each(function (d) {
            d.path = this;
        });

    const node = svg.append("g")
        .selectAll("text")
        .data(root.leaves())
        .join("text")
        .attr("dy", "0.31em")
        .attr("x", d => d.x < Math.PI ? 6 : -6)
        .attr("text-anchor", d => d.x < Math.PI ? "start" : "end")
        .attr("transform", d => `${`rotate(${d.x * 180 / Math.PI - 90}) translate(${d.y},0)`}${d.x >= Math.PI ? " rotate(180)" : ""}`)
        .attr("fill", "currentColor")
        .text(d => d.data.name)
        .each(function (d) {
            d.text = this;
        })
        .on("mouseover", overed)
        .on("mouseout", outed);

    node.append("title")
        .text(d => `Airport: ${d.data.name}
Region: ${d.parent.data.name}
Outgoing routes: ${d.outgoing.length}
Incoming routes: ${d.incoming.length}`);

    function overed(event, d) {
        const connectedPaths = [
            ...d.incoming.map(route => route.path),
            ...d.outgoing.map(route => route.path)
        ];
        const connectedTexts = new Set([
            d.text,
            ...d.incoming.map(([source]) => source.text),
            ...d.outgoing.map(([, target]) => target.text)
        ]);

        d3.selectAll(connectedPaths)
            .attr("stroke", "black")
            .attr("stroke-opacity", 1)
            .raise();

        d3.selectAll(Array.from(connectedTexts))
            .attr("fill", "black")
            .attr("font-weight", "bold");
    }

    function outed(event, d) {
        d3.selectAll([...d.incoming, ...d.outgoing].map(route => route.path))
            .attr("stroke", ([, , airline]) => airlineColor[airline] ?? "#444")
            .attr("stroke-opacity", 0.55);

        d3.selectAll(Array.from(new Set([
            d.text,
            ...d.incoming.map(([source]) => source.text),
            ...d.outgoing.map(([, target]) => target.text)
        ])))
            .attr("fill", "currentColor")
            .attr("font-weight", null);

        link.order();
    }

    return svg.node();
}
